### ISSUE TITLE
Using with Jeyklll

### ISSUE THREAD

**Issue by discorick** [gjtorikian/extended-markdown-filter#12]
I am fairly new to Jekyll, after including extended-markdown-filter to my Gemfile, bundling and adding to extensions I get the following error: 

`undefined method '[]' for nil:NilClass` 

Looking at https://github.com/gjtorikian/extended-markdown-filter#within-jekyll I am not quite sure what it means to pass the context "emf_use_blocks" through the filter.

**Comment by gjtorikian** [comment]
Ah, with Jekyll, this is meant to be used with another plugin in conjunction, https://github.com/gjtorikian/jekyll-html-pipeline. 

A minimum config file might look like:
``` yaml
gems:
  - extended-markdown-filter
  - jekyll-html-pipeline

markdown: HTMLPipeline
html_pipeline:
  filters:
    - "ExtendedMarkdownFilter"
  context:
    emf_use_blocks: true
```

Let me know if that works out for you and I'll update the documentation!
